<?php

/**
 * Implements hook_theme().
 */

function reservation_theme($existing, $type, $theme, $path) {
  return [
    'reservation_list' => [
      'variables' => [
        'items' => [],
        ],
      ],
    ];
}

/**
 * Implements hook_mail_alter().
 */
function reservation_mail_alter (&$message) {
  return [
    'automatic_email' => [
      'variables' => [
        'items'=>[]
      ],
    ],
  ];
}
